# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84535e8cf4dc538dbfd2344f4af31b6014f1c802a45cf7199cacffd2d5f828f0d9b73f2ed86843399c8b2d8d143ead259d9dc2048c649af3e08a3bd276ad5355

test:
  secret_key_base: e4e41bcc7359e44e75cfb5c2f7ba6656c31c4397c7d19fec806ce5c71609705a2d5b17b2aff1456ce8b87b039f3411992f57e9122d69cfe7920ff96449260aa1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
